/*
 * This source file was generated by the Gradle 'init' task
 */
package videonamefixer;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class Main extends Application {
    @Override
    public void start(Stage stage) {
        Button button = new Button("Click Me!");
        button.setOnAction(e -> button.setText("You clicked me!"));

        StackPane root = new StackPane(button);
        Scene scene = new Scene(root, 400, 200);

        stage.setTitle("JavaFX Test App");
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        launch();
    }
}
